import React, { createContext, useContext, useEffect, useMemo } from 'react';
import { useVault } from '@/components/paskey/VaultContext';

const AR = {
  'Vault':'الخزنة','Autofill':'الملء التلقائي','Generator':'المولّد','Security':'الأمان','Settings':'الإعدادات',
  'Search vault':'البحث في الخزنة','Main navigation':'التنقل الرئيسي','Add':'إضافة','Close':'إغلاق','Add item':'إضافة عنصر','Close add menu':'إغلاق قائمة الإضافة','Add item categories':'فئات إضافة العناصر',
  'Your private space':'مساحتك الخاصة','Search PasKey...':'ابحث في PasKey...','No matching items in your vault.':'لا توجد عناصر مطابقة في خزنتك.','Vault secured':'الخزنة مؤمّنة','items':'عناصر','Open the Security Center for your local audit score.':'افتح مركز الأمان للاطلاع على نتيجة التدقيق المحلية.','Favorites':'المفضلة','Recently updated':'تم تحديثها مؤخرًا','Your vault is empty. Tap + to add your first item.':'خزنتك فارغة. اضغط + لإضافة أول عنصر.',
  'Passwords':'كلمات المرور','Email & Google':'البريد الإلكتروني وGoogle','Social Media':'وسائل التواصل','Banking':'الخدمات المصرفية','Cards':'البطاقات','Addresses':'العناوين','Secure Notes':'الملاحظات الآمنة',
  'PasKey preferences':'تفضيلات PasKey','Appearance':'المظهر','Vault':'الخزنة','Privacy & platform':'الخصوصية والمنصة','Danger zone':'منطقة الخطر','Biometric unlock':'فتح القفل بالقياسات الحيوية','Auto lock':'القفل التلقائي','Clear clipboard after':'مسح الحافظة بعد','Screenshot protection':'حماية لقطات الشاشة','Require authentication to reveal secrets':'طلب المصادقة لإظهار البيانات السرية','Color theme':'نمط الألوان','Encrypted backup':'نسخة احتياطية مشفرة','Restore from backup':'استعادة من نسخة احتياطية','Privacy & local data':'الخصوصية والبيانات المحلية','Erase local vault':'مسح الخزنة المحلية','Export':'تصدير','Restore':'استعادة','Language':'اللغة','English':'English','Arabic':'العربية',
  'Immediately':'فورًا','1 minute':'دقيقة واحدة','5 minutes':'5 دقائق','15 minutes':'15 دقيقة','30 minutes':'30 دقيقة','Never':'أبدًا','15 seconds':'15 ثانية','30 seconds':'30 ثانية','60 seconds':'60 ثانية','System':'النظام','Dark':'داكن','Cream':'كريمي','Pro':'احترافي',
  'Create your Master Password':'أنشئ كلمة المرور الرئيسية','Master Password':'كلمة المرور الرئيسية','Confirm':'تأكيد','Suggest a strong password':'اقترح كلمة مرور قوية','Create vault':'إنشاء الخزنة','Creating vault…':'جارٍ إنشاء الخزنة…','Welcome back':'مرحبًا بعودتك','Unlock your PasKey vault.':'افتح خزنة PasKey.','Use fingerprint or secure face':'استخدم البصمة أو الوجه الآمن','Waiting for Android…':'بانتظار Android…','Unlock with Master Password':'فتح بكلمة المرور الرئيسية','Unlocking…':'جارٍ فتح القفل…',
  'Password Generator':'مولّد كلمات المرور','Generated locally with a cryptographically secure RNG.':'يتم التوليد محليًا باستخدام مولّد عشوائي آمن تشفيريًا.','Copy':'نسخ','Copied':'تم النسخ','Regenerate':'إعادة التوليد','Length':'الطول','Uppercase (A–Z)':'أحرف كبيرة (A–Z)','Lowercase (a–z)':'أحرف صغيرة (a–z)','Numbers (0–9)':'أرقام (0–9)','Symbols (!@#$)':'رموز (!@#$)',
  'Saved Logins':'بيانات الدخول المحفوظة','Store and manage sign-ins for websites and Android apps.':'احفظ وأدر بيانات الدخول للمواقع وتطبيقات Android.','Save':'حفظ','Search saved logins':'البحث في بيانات الدخول المحفوظة','Passwords hidden':'كلمات المرور مخفية','No saved logins yet':'لا توجد بيانات دخول محفوظة بعد','Save a login':'حفظ بيانات دخول','Website':'موقع ويب','Android app':'تطبيق Android','Email':'البريد الإلكتروني','Username':'اسم المستخدم','Phone':'الهاتف','Password':'كلمة المرور','Identity':'الهوية','Identity type':'نوع الهوية','Target type':'نوع الهدف','Domain':'النطاق','Package name':'اسم الحزمة','Save login':'حفظ بيانات الدخول','Saving…':'جارٍ الحفظ…',
  'PasKey Autofill':'الملء التلقائي في PasKey','Autofill save is ready':'الحفظ التلقائي جاهز','Android Autofill is not enabled for PasKey':'الملء التلقائي في Android غير مفعّل لـ PasKey','Enable PasKey once in Android settings so save and login suggestions can appear in apps and websites.':'فعّل PasKey مرة واحدة من إعدادات Android حتى تظهر اقتراحات الحفظ وتسجيل الدخول داخل التطبيقات والمواقع.','Enable PasKey Autofill':'تفعيل الملء التلقائي لـ PasKey','Opening Android settings…':'جارٍ فتح إعدادات Android…','Choose PasKey as your Android Autofill service, then return here.':'اختر PasKey كخدمة الملء التلقائي في Android ثم عد إلى هنا.','Could not open Android Autofill settings.':'تعذر فتح إعدادات الملء التلقائي في Android.',"After a supported login, approve Android's save prompt. PasKey can offer it immediately; import only adds it to your main vault.":'بعد تسجيل الدخول في تطبيق أو موقع مدعوم، وافق على طلب الحفظ من Android. يستطيع PasKey اقتراح بيانات الدخول مباشرة، والاستيراد يضيفها فقط إلى خزنتك الرئيسية.','Import saved login':'استيراد بيانات الدخول المحفوظة','Importing saved logins…':'جارٍ استيراد بيانات الدخول المحفوظة…','saved logins':'بيانات دخول محفوظة','Add Autofill login':'إضافة بيانات دخول للملء التلقائي','Link one permanent login to one exact website or Android app.':'اربط بيانات دخول دائمة بموقع محدد أو تطبيق Android محدد.','Close login form':'إغلاق نموذج بيانات الدخول','Enter an email, username, or phone number.':'أدخل بريدًا إلكترونيًا أو اسم مستخدم أو رقم هاتف.','Enter a permanent password or login code.':'أدخل كلمة مرور دائمة أو رمز دخول.','Enter an exact domain or Android package.':'أدخل نطاق الموقع أو اسم حزمة Android بدقة.','Choose an image file for the local profile photo.':'اختر ملف صورة لصورة الحساب المحلية.','Choose an image smaller than 750 KB.':'اختر صورة أصغر من 750 كيلوبايت.','Could not read the selected image.':'تعذر قراءة الصورة المحددة.','Identity, password, and an exact website or Android package are required.':'الهوية وكلمة المرور ونطاق الموقع أو حزمة Android مطلوبة.','Could not save this login. Your entries were kept; please try again.':'تعذر حفظ بيانات الدخول. تم الاحتفاظ بالمدخلات؛ حاول مرة أخرى.','Replace selected local photo':'استبدال الصورة المحلية المحددة','Choose a local profile photo (optional)':'اختيار صورة حساب محلية (اختياري)','Remove selected photo':'إزالة الصورة المحددة','Could not import saved logins. Your existing vault data is unchanged; please try again.':'تعذر استيراد بيانات الدخول المحفوظة. بيانات الخزنة الحالية لم تتغير؛ حاول مرة أخرى.','No new Android saves were waiting to import.':'لا توجد بيانات دخول جديدة محفوظة في Android بانتظار الاستيراد.',"Save one manually, or approve Android's Autofill save prompt after signing in.":'احفظ بيانات الدخول يدويًا، أو وافق على طلب الحفظ التلقائي من Android بعد تسجيل الدخول.','Needs identity and target':'تحتاج إلى هوية وهدف','No email, username, or phone saved':'لا يوجد بريد أو اسم مستخدم أو هاتف محفوظ',
  'Back':'رجوع','Edit item':'تعديل العنصر','Delete item':'حذف العنصر','Toggle favorite':'تبديل المفضلة','Open website':'فتح الموقع','Cancel':'إلغاء','Delete':'حذف','Favorite':'مفضلة','New':'جديد','Edit':'تعديل','Save to vault':'حفظ في الخزنة','Encrypting…':'جارٍ التشفير…','Generate password':'توليد كلمة مرور','Unknown category.':'فئة غير معروفة.','Decrypting…':'جارٍ فك التشفير…',
  'encrypted':'مشفّر','is required.':'مطلوب.','Unable to open this item.':'تعذر فتح هذا العنصر.','Unable to save this item. Please try again.':'تعذر حفظ هذا العنصر. حاول مرة أخرى.',
  'Login label':'اسم بيانات الدخول','Service / provider':'الخدمة / المزوّد','Account label (Personal, Work…)':'تسمية الحساب (شخصي، عمل…)','Local profile photo (optional)':'صورة الحساب المحلية (اختياري)','Website (comma-separated if needed)':'الموقع الإلكتروني (افصل بفاصلة عند الحاجة)','Android app package (comma-separated if needed)':'حزمة تطبيق Android (افصل بفاصلة عند الحاجة)','Email address':'عنوان البريد الإلكتروني','Phone number':'رقم الهاتف','Notes':'ملاحظات','Tags (comma separated)':'الوسوم (مفصولة بفواصل)','Auto-detect from website or Android app':'اكتشاف تلقائي من الموقع أو تطبيق Android','Other website or app':'موقع أو تطبيق آخر','Choose a local profile photo':'اختر صورة حساب محلية','Saved encrypted in PasKey. Photos from other apps are never read automatically.':'تُحفظ الصورة مشفّرة داخل PasKey، ولا تتم قراءة صور التطبيقات الأخرى تلقائيًا.',
  'Account name':'اسم الحساب','Recovery email':'بريد الاسترداد','Recovery phone':'هاتف الاسترداد','Platform / label':'المنصة / التسمية','Account label (Personal, Creator…)':'تسمية الحساب (شخصي، منشئ محتوى…)','Bank name':'اسم البنك','Account holder':'صاحب الحساب','Account number':'رقم الحساب','PIN':'الرقم السري PIN','SWIFT / BIC':'SWIFT / BIC','Card name':'اسم البطاقة','Cardholder':'اسم حامل البطاقة','Card number':'رقم البطاقة','Expiry (MM/YY)':'تاريخ الانتهاء (MM/YY)','CVV':'رمز CVV','Full name':'الاسم الكامل','Country':'الدولة','City':'المدينة','Address':'العنوان','Postal code':'الرمز البريدي','Title':'العنوان','Content':'المحتوى',
  'Running local analysis…':'جارٍ إجراء التحليل المحلي…','Local protection':'حماية محلية','Security Center':'مركز الأمان','Analysis runs entirely on this device. Nothing is uploaded.':'يعمل التحليل بالكامل على هذا الجهاز. لا يتم رفع أي بيانات.','Security Score':'درجة الأمان','Weak passwords':'كلمات مرور ضعيفة','Reused passwords':'كلمات مرور معاد استخدامها','Items missing a password':'عناصر بدون كلمة مرور','Not updated in over a year':'لم تُحدّث منذ أكثر من سنة','None':'لا يوجد','Enabled':'مفعّل','Off':'متوقف','Nothing saved here yet.':'لا توجد عناصر محفوظة هنا بعد.',
  'Change':'تغيير','Update Master Password':'تحديث كلمة المرور الرئيسية','Current Master Password':'كلمة المرور الرئيسية الحالية','New Master Password':'كلمة المرور الرئيسية الجديدة','Strength:':'القوة:','Erase local vault?':'مسح الخزنة المحلية؟','Continue':'متابعة','Are you absolutely sure?':'هل أنت متأكد تمامًا؟','Erase forever':'مسح نهائي','Erasing…':'جارٍ المسح…','Show':'إظهار','Hide':'إخفاء',
  'Empty':'فارغة','Weak':'ضعيفة','Fair':'مقبولة','Good':'جيدة','Strong':'قوية','Very Strong':'قوية جدًا',
  'Native Android requirement.':'متطلب Android الأصلي.','Biometric status is read from BiometricManager and background locking is driven by the Android activity lifecycle in the production build; this layer reflects your saved preference only.':'تتم قراءة حالة القياسات الحيوية من BiometricManager، ويتم قفل التطبيق في الخلفية وفق دورة حياة نشاط Android في نسخة الإنتاج؛ وتعكس هذه الطبقة تفضيلك المحفوظ فقط.',
  'Use a fingerprint or supported secure face unlock on your device. Your Master Password always remains available.':'استخدم بصمة الإصبع أو فتح الوجه الآمن المدعوم على جهازك. وتبقى كلمة المرور الرئيسية متاحة دائمًا.',
  'Autofill and the biometric prompt run in the native Android layer. Each Autofill choice is authenticated before PasKey returns any saved value to another app or website.':'يعمل الملء التلقائي وطلب القياسات الحيوية في طبقة Android الأصلية. تتم المصادقة على كل اختيار للملء التلقائي قبل أن يعيد PasKey أي قيمة محفوظة إلى تطبيق أو موقع آخر.',
  'Encrypted backup created.':'تم إنشاء النسخة الاحتياطية المشفّرة.','Unable to create encrypted backup.':'تعذر إنشاء النسخة الاحتياطية المشفّرة.','Unable to restore this backup.':'تعذر استعادة هذه النسخة الاحتياطية.','Biometric unlock was disabled. Your Master Password still protects the vault.':'تم تعطيل فتح القفل بالقياسات الحيوية. ما زالت كلمة المرور الرئيسية تحمي الخزنة.',
  'The backup contains encrypted vault records, never the Master Password or plaintext CSV data.':'تحتوي النسخة الاحتياطية على سجلات الخزنة المشفّرة فقط، ولا تتضمن كلمة المرور الرئيسية أو بيانات CSV بنص صريح.',
  'Erasing your vault permanently removes its encrypted records, native Autofill cache and biometric unlock wrapper from this device. There is no cloud copy and no recovery.':'يؤدي مسح الخزنة نهائيًا إلى إزالة سجلاتها المشفّرة وذاكرة الملء التلقائي المحلية وبيانات فتح القفل الحيوي من هذا الجهاز. لا توجد نسخة سحابية ولا إمكانية للاسترداد.',
  'PasKey · local-first vault':'PasKey · خزنة محلية أولًا',
  'New Master Password must be at least 12 characters.':'يجب ألا تقل كلمة المرور الرئيسية الجديدة عن 12 حرفًا.','Incorrect Master Password. Unable to unlock PasKey.':'كلمة المرور الرئيسية غير صحيحة. تعذر فتح PasKey.','Master Password updated. Your vault key was re-wrapped — all items remain accessible.':'تم تحديث كلمة المرور الرئيسية وإعادة تغليف مفتاح الخزنة، وتظل جميع العناصر متاحة.',
  'This permanently erases the encrypted vault, native Autofill cache and biometric unlock wrapper from this device. There is no cloud copy and no recovery.':'سيؤدي هذا إلى مسح الخزنة المشفّرة وذاكرة الملء التلقائي المحلية وبيانات فتح القفل الحيوي من هذا الجهاز نهائيًا. لا توجد نسخة سحابية ولا إمكانية للاسترداد.',
  'Type':'اكتب','to confirm.':'للتأكيد.','Type ERASE to confirm':'اكتب ERASE للتأكيد',
};
const Ctx=createContext({language:'en',t:(s)=>s});
export function I18nProvider({children}) {
 const {settings,updateSettings}=useVault();
 const language=settings.language==='ar'?'ar':'en';
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';},[language]);
 const value=useMemo(()=>({language,setLanguage:(v)=>updateSettings({language:v}),t:(s)=>language==='ar'?(AR[s]||s):s}),[language,updateSettings]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export const useI18n=()=>useContext(Ctx);
